# Generated by Django 3.2.11 on 2024-01-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_rename_item_orderitem_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='item',
        ),
    ]
