# Generated by Django 4.2.9 on 2024-01-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0030_theme_collapsible_stacked_inlines_and_more"),
        ("bookapp", "0007_order_billing_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="t",
            fields=[
                (
                    "theme_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="admin_interface.theme",
                    ),
                ),
            ],
            bases=("admin_interface.theme",),
        ),
    ]
