# Generated by Django 4.2.9 on 2024-01-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0008_t"),
    ]

    operations = [
        migrations.DeleteModel(
            name="t",
        ),
    ]
