# Generated by Django 4.2.9 on 2024-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0010_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
