# Generated by Django 4.2.9 on 2024-01-28 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0011_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trx",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
