# Generated by Django 4.2.9 on 2024-01-28 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0012_order_trx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="trx",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
