# Generated by Django 4.2.9 on 2024-01-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0013_alter_order_trx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="trx",
        ),
    ]
