# Generated by Django 4.2.9 on 2024-01-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0014_remove_order_trx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
    ]
